### ISSUE TITLE
Cannot catch events on target stream 

### ISSUE THREAD

**Issue by doArcanjo** [felixge/node-combined-stream#20]
//Only 'pipe Event is being triggered;

postgres_copy_table_stream.on('finish', function())
combinedStream.pipe(postgres_copy_table_stream);

.: finish event is not being emited;

**Comment by apechimp** [comment]
There's not really enough information here for me to figure out why the `finish` event isn't being emitted. Can you provide more detailed reproduction steps? Also, you may want to use a different library based on streams 2 instead of this one (see #21 for details).

**Comment by apechimp** [comment]
Please reopen if you want to provide more details. Thanks for the bug report: sorry I can't be of help with what you've provided.
