### ISSUE TITLE
Streams appended without line breaks...

### ISSUE THREAD

**Issue by jkrinsky** [felixge/node-combined-stream#43]
I am using node-combined-stream in combination with[ node-csv-parse](https://github.com/adaltas/node-csv-parse) and, after many hours of alternately scratching and pounding my head, I realized that the second/subsequent streams were getting appended without line breaks, so whenever there was a transition from one stream to another, there would be two csv lines in one. I added the following which fixed the problem. 

`
            firstStream.on('end', function(){
                ...
                combinedStream.write('\n');
            });
`

Expected behavior?

**Comment by apechimp** [comment]
Yes. This is expected. For CSV data, this is understandably annoying. Keep in mind that the stream concept is very general, so even though you'd want newlines in for CSVs, you can use this library for any kind of data.
